export default [
    { "date": "2024-01-01", "localName": "New Year's Day", "name": "New Year's Day" },
    { "date": "2024-01-08", "localName": "Epiphany", "name": "Epiphany" },
    { "date": "2024-01-12", "localName": "Swami Vivekananda Jayanti", "name": "Swami Vivekananda Jayanti" },
    { "date": "2024-01-13", "localName": "Lohri", "name": "Lohri" },
    { "date": "2024-01-14", "localName": "Makar Sankranti", "name": "Makar Sankranti" },
    { "date": "2024-01-26", "localName": "Republic Day", "name": "Republic Day" },
    { "date": "2024-01-31", "localName": "Vasant Panchami", "name": "Vasant Panchami" },
    { "date": "2024-02-14", "localName": "Valentine's Day", "name": "Valentine's Day" },
    { "date": "2024-03-08", "localName": "Holi", "name": "Holi" },
    { "date": "2024-03-17", "localName": "St. Patrick's Day", "name": "St. Patrick's Day" },
    { "date": "2024-03-22", "localName": "Good Friday", "name": "Good Friday" },
    { "date": "2024-03-29", "localName": "Ram Navami", "name": "Ram Navami" },
    { "date": "2024-04-08", "localName": "Mahavir Jayanti", "name": "Mahavir Jayanti" },
    { "date": "2024-04-14", "localName": "Ambedkar Jayanti", "name": "Ambedkar Jayanti" },
    { "date": "2024-05-01", "localName": "Labour Day", "name": "Labour Day" },
    { "date": "2024-05-08", "localName": "Buddha Purnima", "name": "Buddha Purnima" },
    { "date": "2024-05-23", "localName": "Eid-ul-Fitr", "name": "Eid-ul-Fitr" },
    { "date": "2024-06-15", "localName": "Eid-ul-Adha", "name": "Eid-ul-Adha" },
    { "date": "2024-07-01", "localName": "Bank Holiday", "name": "Bank Holiday" },
    { "date": "2024-08-15", "localName": "Independence Day", "name": "Independence Day" },
    { "date": "2024-08-19", "localName": "Janmashtami", "name": "Janmashtami" },
    { "date": "2024-09-17", "localName": "Ganesh Chaturthi", "name": "Ganesh Chaturthi" },
    { "date": "2024-10-02", "localName": "Gandhi Jayanti", "name": "Gandhi Jayanti" },
    { "date": "2024-10-11", "localName": "Dussehra", "name": "Dussehra" },
    { "date": "2024-10-24", "localName": "Durga Puja", "name": "Durga Puja" },
    { "date": "2024-10-31", "localName": "Halloween", "name": "Halloween" },
    { "date": "2024-11-01", "localName": "Diwali", "name": "Diwali" },
    { "date": "2024-11-02", "localName": "Bhai Dooj", "name": "Bhai Dooj" },
    { "date": "2024-11-15", "localName": "Guru Nanak Jayanti", "name": "Guru Nanak Jayanti" },
    { "date": "2024-12-01", "localName": "Christmas Eve", "name": "Christmas Eve" },
    { "date": "2024-12-25", "localName": "Christmas Day", "name": "Christmas Day" },
    { "date": "2024-12-31", "localName": "New Year's Eve", "name": "New Year's Eve" },
    { "date": "2024-01-07", "localName": "Bhogi", "name": "Bhogi" },
    { "date": "2024-02-10", "localName": "Maha Shivaratri", "name": "Maha Shivaratri" },
    { "date": "2024-04-04", "localName": "Good Friday", "name": "Good Friday" },
    { "date": "2024-04-05", "localName": "Easter", "name": "Easter" },
    { "date": "2024-05-05", "localName": "Cinco de Mayo", "name": "Cinco de Mayo" },
    { "date": "2024-05-29", "localName": "Ascension Day", "name": "Ascension Day" },
    { "date": "2024-06-01", "localName": "Corpus Christi", "name": "Corpus Christi" },
    { "date": "2024-07-15", "localName": "Parsi New Year", "name": "Parsi New Year" },
    { "date": "2024-08-09", "localName": "Krishna Janmashtami", "name": "Krishna Janmashtami" },
    { "date": "2024-09-29", "localName": "Eid-e-Milad", "name": "Eid-e-Milad" },
    { "date": "2024-10-15", "localName": "Maha Navami", "name": "Maha Navami" },
    { "date": "2024-11-02", "localName": "Chhath Puja", "name": "Chhath Puja" },
    { "date": "2024-11-21", "localName": "Dussehra", "name": "Dussehra" },
    { "date": "2024-12-24", "localName": "Christmas Eve", "name": "Christmas Eve" },
    { "date": "2024-12-30", "localName": "New Year's Eve", "name": "New Year's Eve" },
    { "date": "2024-01-30", "localName": "Martyrs' Day", "name": "Martyrs' Day" },
    { "date": "2024-03-19", "localName": "Chaitra Navratri", "name": "Chaitra Navratri" },
    { "date": "2024-05-07", "localName": "Eid al-Fitr", "name": "Eid al-Fitr" },
    { "date": "2024-07-16", "localName": "Nag Panchami", "name": "Nag Panchami" },
    { "date": "2024-08-28", "localName": "Raksha Bandhan", "name": "Raksha Bandhan" },
    { "date": "2024-09-07", "localName": "Ganesh Chaturthi", "name": "Ganesh Chaturthi" },
    { "date": "2024-10-11", "localName": "Durga Puja", "name": "Durga Puja" },
    { "date": "2024-11-12", "localName": "Diwali", "name": "Diwali" },
    { "date": "2024-12-14", "localName": "Gita Jayanti", "name": "Gita Jayanti" }
  ];
  